modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="alien_dispute"
version="1.0.0"
displayName="Alien_Dispute"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.alien_dispute]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.alien_dispute]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.alien_dispute]]
    modId="playeranimator"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block custom mixins
# End of user code block custom mixins


# Start of user code block dependencies configuration
# End of user code block dependencies configuration